AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template to deploy Mini Roteiro Contábil (Ingest + Processor Lambdas, S3, SQS, DynamoDB, EventBridge).

Globals:
  Function:
    Timeout: 30
    Runtime: dotnet8
    Architectures:
      - x86_64

Resources:

  AccountingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub AccountingQueue-DLQ-${AWS::AccountId}-${AWS::Region}

  AccountingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub AccountingQueue-${AWS::AccountId}-${AWS::Region}
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AccountingDLQ.Arn
        maxReceiveCount: 5

  S3ToSqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AccountingQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3SendMessage
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt AccountingQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:s3:::accounting-batch-${AWS::AccountId}-${AWS::Region}
          - Sid: AllowEventsSendMessage
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt AccountingQueue.Arn

  AccountingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub accounting-batch-${AWS::AccountId}-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt AccountingQueue.Arn

  AccountingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub AccountingEntries-${AWS::AccountId}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: EntryId
          AttributeType: S
        - AttributeName: BatchId
          AttributeType: S
      KeySchema:
        - AttributeName: EntryId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: BatchId-index
          KeySchema:
            - AttributeName: BatchId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  IngestLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: IngestSqsSend
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt AccountingQueue.Arn

  ProcessorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ProcessorSQSPerms
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt AccountingQueue.Arn
        - PolicyName: ProcessorS3Read
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: !Sub arn:aws:s3:::accounting-batch-${AWS::AccountId}-${AWS::Region}/*
        - PolicyName: ProcessorDDBWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource:
                  - !GetAtt AccountingTable.Arn
                  - !Sub ${AccountingTable.Arn}/index/BatchId-index

  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ingest-api-lambda
      CodeUri: src/Accounting.IngestLambda/
      Handler: Accounting.IngestLambda::Accounting.IngestLambda.Function::Handler
      Role: !GetAtt IngestLambdaRole.Arn
      Environment:
        Variables:
          SQS_URL: !Ref AccountingQueue
      Events:
        Api:
          Type: Api
          Properties:
            Path: /ingest
            Method: post

  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: processor-lambda
      CodeUri: src/Accounting.ProcessorLambda/
      Handler: Accounting.ProcessorLambda::Accounting.ProcessorLambda.Function::FunctionHandler
      Role: !GetAtt ProcessorLambdaRole.Arn
      Environment:
        Variables:
          DDB_TABLE: !Ref AccountingTable
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt AccountingQueue.Arn
            BatchSize: 5

  QueryLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: QueryDDB
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource:
                  - !GetAtt AccountingTable.Arn
                  - !Sub ${AccountingTable.Arn}/index/BatchId-index

  QueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: query-lambda
      CodeUri: src/Accounting.QueryLambda/
      Handler: Accounting.QueryLambda::Accounting.QueryLambda.Function::Handler
      Role: !GetAtt QueryLambdaRole.Arn
      Environment:
        Variables:
          DDB_TABLE: !Ref AccountingTable
      Events:
        ApiGetEntries:
          Type: Api
          Properties:
            Path: /entries/{batchId}
            Method: get

  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Name: scheduled-ingest-rule
      ScheduleExpression: rate(15 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt AccountingQueue.Arn
          Id: SendToSQS
          Input: '{"scheduled":true}'

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint (POST /ingest)"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ingest"

  S3BucketName:
    Description: "S3 bucket name for batch uploads"
    Value: !Ref AccountingBucket

  SQSQueueUrl:
    Description: "SQS Queue URL"
    Value: !Ref AccountingQueue

  DynamoDBTableName:
    Description: "DynamoDB table name"
    Value: !Ref AccountingTable